version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: queries_challenge
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: queries_challenge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
